import { NestFactory } from "@nestjs/core";
import { config } from 'dotenv';

import { AppModule } from "./app.module"
import { DocumentBuilder } from "@nestjs/swagger/dist/document-builder";
import { SwaggerModule } from "@nestjs/swagger/dist/swagger-module";

config();

declare const module: any;

async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.enableCors();
    app.setGlobalPrefix('api');

    const options = new DocumentBuilder()
        .setTitle('Conduit API')
        .setDescription('Conduit API documentation')
        .setVersion('1.0')
        .setExternalDoc('RealWorld - Website', 'https://realworld-docs.netlify.app/')
        .setLicense('MIT License', 'https://opensource.org/license/mit/')
        .addBearerAuth(
            {
                type: 'apiKey',
                scheme: 'bearer',
                bearerFormat: 'JWT',
                name: 'Authorization',
                description: `For accessing the protected API resources,
                 you must have received a a valid JWT token after registering or logging in.
                  This JWT token must then be used for all protected resources by passing it in via the
                   'Authorization' header.
                A JWT token is generated by the API by either registering via / users or logging in via / users / login.
                The following format must be in the 'Authorization' header : 
                
                Token xxxxxx.yyyyyyy.zzzzzz
                `,
                in: 'header',
            },
            'Token',)

        .addServer('http://localhost:3000/api')
        .addTag('Realworld')
        .build()

    const document = SwaggerModule.createDocument(app, options, {
        ignoreGlobalPrefix: true,
    });
    SwaggerModule.setup('api-docs', app, document);

    if (module.hot) {
        module.hot.accept();
        module.hot.dispose(() => app.close());
    }

    await app.listen(3000);
}


bootstrap();